Enable c programming exercise template again on Jenkins setup (#2697)

diff --git a/src/main/resources/templates/jenkins/c/Jenkinsfile b/src/main/resources/templates/jenkins/c/Jenkinsfile
--- a/src/main/resources/templates/jenkins/c/Jenkinsfile
+++ b/src/main/resources/templates/jenkins/c/Jenkinsfile
@@ -24,77 +24,72 @@ pipeline {
             stage('Build') {
                 steps {
                     timestamps {
-                        sh '''
+                        sh  '''
                             cd $WORKSPACE
-                            echo &quot;--------------------setup-------------------&quot;
-                            echo &quot;User:&quot;
-                            whoami
-                            echo &quot;Updating assignment and test-reports ownership...&quot;
-                            echo &quot;--------------------setup-------------------&quot;
-                            echo &quot;--------------------info--------------------&quot;
-                            python3 --version
-                            pip3 --version
-                            gcc --version
-                            # Generic debug infos:
-                            # tree
-                            echo &quot;--------------------tests-------------------&quot;
-                            ls -la tests
-                            echo &quot;--------------------tests-------------------&quot;
-                            echo &quot;--------------------assignment--------------&quot;
-                            ls -la assignment
-                            echo &quot;--------------------assignment--------------&quot;
+                            # Updating assignment and test-reports ownership...
+                            sudo chown artemis_user:artemis_user assignment/ -R
+                            sudo rm -rf test-reports
+                            sudo mkdir test-reports
+                            sudo chown artemis_user:artemis_user test-reports/ -R
 
+                            # assignment
                             cd tests
                             REQ_FILE=requirements.txt
-                            if [ -f &quot;$REQ_FILE&quot; ]; then
+                            if [ -f "$REQ_FILE" ]; then
                                 pip3 install --user -r requirements.txt
                             else
-                                echo &quot;$REQ_FILE does not exist&quot;
+                                echo "$REQ_FILE does not exist"
                             fi
                             exit 0
-                           '''
-                        sh '''
+                            '''
+                        sh  '''
                             #!/usr/bin/env bash
 
-                            shadowFilePath=&quot;../tests/testUtils/c/shadow_exec.c&quot;
+                            shadowFilePath="../tests/testUtils/c/shadow_exec.c"
 
-                            foundIncludeDirs=`grep -m 1 &apos;INCLUDEDIRS\s*=&apos; assignment/Makefile`
-                            echo &quot;Include: $foundIncludeDirs&quot;
+                            foundIncludeDirs=`grep -m 1 'INCLUDEDIRS\s*=' assignment/Makefile`
 
-                            foundSource=`grep -m 1 &apos;SOURCE\s*=&apos; assignment/Makefile`
-                            foundSource=&quot;$foundSource $shadowFilePath&quot;
-                            echo &quot;Source: $foundSource&quot;
+                            foundSource=`grep -m 1 'SOURCE\s*=' assignment/Makefile`
+                            foundSource="$foundSource $shadowFilePath"
 
                             rm -f assignment/GNUmakefile
-                            rm -f assignment/Makefile
+                            rm -f assignment/makefile
 
                             cp -f tests/Makefile assignment/Makefile || exit 2
-                            sed -i &quot;s~INCLUDEDIRS\s*=.*~${foundIncludeDirs}~; s~SOURCE\s*=.*~${foundSource}~&quot; assignment/Makefile
-                           '''
-                        sh '''
+                            sed -i "s~\bINCLUDEDIRS\s*=.*~${foundIncludeDirs}~; s~\bSOURCE\s*=.*~${foundSource}~" assignment/Makefile
+                            '''
+                        sh  '''
                             #!/bin/bash
 
-                            # Actual build process:
-                            cd tests
-
-                            python3 Tests.py s
-                            rm Tests.py
-                            rm -rf ./tests
-
-                            exit 0
-                           '''
+                            gcc -c -Wall assignment/*.c || error=true
+                            if [ ! $error ]
+                            then
+                                # Actual build process:
+                                cd tests
+                                python3 Tests.py s
+                                rm Tests.py
+                                rm -rf ./tests
+                                exit 0
+                            else
+                                # Compilaton error
+                                exit 1
+                            fi
+                            '''
                     }
                 }
             }
         }
         post {
             cleanup {
-                sh '''
-                   sed -i &apos;s/&#x1b;//g&apos; test-reports/tests-results.xml&#xd;
-                   sed -i &apos;s/&lt;skipped/&lt;error/g&apos; test-reports/tests-results.xml&#xd;
-                   sed -i &apos;s/&lt;\/skipped&gt;/&lt;\/error&gt;/g&apos; test-reports/tests-results.xml&#xd;
-                   mv test-reports results
-                   '''
+                sh  '''
+                    if [ -e test-reports/tests-results.xml ]
+                    then
+                        sed -i 's/&#x1b;//g' test-reports/tests-results.xml
+                        sed -i 's/<skipped/<error/g' test-reports/tests-results.xml
+                        sed -i 's/<\/skipped>/<\/error>/g' test-reports/tests-results.xml
+                    fi
+                    mv test-reports results
+                    '''
                 sendTestResults credentialsId: '#jenkinsNotificationToken', notificationUrl: '#notificationsUrl'
                 cleanWs()
             }
