Programming Exercises: Implement build failure not depending on existence of test feedback

diff --git a/src/main/resources/templates/aeolus/empty/default.yaml b/src/main/resources/templates/aeolus/empty/default.yaml
--- a/src/main/resources/templates/aeolus/empty/default.yaml
+++ b/src/main/resources/templates/aeolus/empty/default.yaml
@@ -11,6 +11,16 @@ actions:
   - name: run_tests
     script: |-
       # TODO: Run the tests and generate JUnit XMLs
+      # Example pattern for exit codes:
+      #
+      # <compile_command>
+      # COMPILATION_EXIT_CODE=$?
+      #
+      # if [ $COMPILATION_EXIT_CODE -ne 0 ]; then
+      #     exit 1
+      # fi
+      #
+      # <test_command> || true
       echo 'Hello World'
   - name: process_results
     script: |-
