`Development`: Execute Architecture tests during java style action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -209,6 +209,15 @@ jobs:
     - name: Java Documentation
       run: ./gradlew checkstyleMain -x webapp
       if: success() || failure()
+    - name: Java Architecture Tests
+      run: ./gradlew test --tests "de.tum.in.www1.artemis.ArchitectureTest" -x webapp
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Java Architecture Tests
+        path: build/test-results/test/*.xml
+        reporter: java-junit
 
   client-tests:
     runs-on: ubuntu-latest
