Revert "Extract test execution into action for reuse"
This reverts commit 35cce9a45bcd92f25089741e6f837b1b67a327a8.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -49,10 +49,18 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 60
     steps:
-    - name: Run server-tests
-      uses: './.github/actions/run-test'
+    - uses: actions/checkout@v3
+    - name: Setup Java
+      uses: actions/setup-java@v3
       with:
-        database: H2
+        distribution: 'temurin'
+        java-version: '${{ env.java }}'
+        cache: 'gradle'
+    - name: Java Tests
+      run: ./gradlew --console=plain test jacocoTestReport -x webapp jacocoTestCoverageVerification | tee tests.log
+    - name: Print failed tests
+      if: failure()
+      run: cat tests.log | grep "Test >.* FAILED" || [[ $? == 1 ]]
     - name: "Codacy: Report coverage"
       uses: codacy/codacy-coverage-reporter-action@master
       with:
@@ -66,6 +74,16 @@ jobs:
         access-token: ${{ secrets.GITHUB_TOKEN }}
         path: build/test-results/test/*.xml
         numFailures: 99
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: H2 Tests
+        path: build/test-results/test/*.xml
+        reporter: java-junit
+    - name: Number of Server Starts
+      if: success() || failure()
+      run: bash supporting_scripts/extract_number_of_server_starts.sh
 
   server-tests-mysql:
       needs: [ server-tests ]
@@ -75,10 +93,51 @@ jobs:
       concurrency:
           group: server-tests-mysql
       steps:
-          - name: Run server-tests
-            uses: './.github/actions/run-test'
+          - uses: actions/checkout@v3
+          - name: Setup Java
+            uses: actions/setup-java@v3
             with:
-                database: MySQL
+                distribution: 'temurin'
+                java-version: '${{ env.java }}'
+                cache: 'gradle'
+          - name: Java Tests
+            id: tests
+            run: set -o pipefail && SPRING_PROFILES_INCLUDE=mysql ./gradlew --console=plain test jacocoTestReport -x webapp jacocoTestCoverageVerification | tee tests.log
+          - name: Print failed tests
+            if: failure()
+            run: cat tests.log | grep "Test >.* FAILED" || [[ $? == 1 ]]
+          - name: Count failed tests
+            id: failedTestCounter
+            if: failure()
+            run: echo "FAILED_TESTS_COUNT=$(cat tests.log | grep "Test >.* FAILED" | wc -l)" >> $GITHUB_OUTPUT
+          - name: Report action failure
+            if: failure()
+            uses: Sibz/github-status-action@v1
+            with:
+                authToken: ${{secrets.GITHUB_TOKEN}}
+                context: 'Test Run - MySQL'
+                description: '❌ ${{ steps.failedTestCounter.outputs.FAILED_TESTS_COUNT }} failed test(s)'
+                state: 'failure'
+                sha: ${{github.event.pull_request.head.sha || github.sha}}
+          - name: Report action success
+            if: success()
+            uses: Sibz/github-status-action@v1
+            with:
+                authToken: ${{secrets.GITHUB_TOKEN}}
+                context: 'Test Run - MySQL'
+                description: '✅ Test succeeded'
+                state: 'success'
+                sha: ${{github.event.pull_request.head.sha || github.sha}}
+          - name: Test Report
+            uses: dorny/test-reporter@v1
+            if: success() || failure()    # run this step even if previous step failed
+            with:
+                name: MySQL Tests
+                path: build/test-results/test/*.xml
+                reporter: java-junit
+          - name: Number of Server Starts
+            if: success() || failure()
+            run: bash supporting_scripts/extract_number_of_server_starts.sh
 
   server-tests-postgres:
       needs: [ server-tests ]
@@ -88,10 +147,51 @@ jobs:
       concurrency:
           group: server-tests-postgres
       steps:
-          - name: Run server-tests
-            uses: './.github/actions/run-test'
+          - uses: actions/checkout@v3
+          - name: Setup Java
+            uses: actions/setup-java@v3
             with:
-                database: PostgreSQL
+                distribution: 'temurin'
+                java-version: '${{ env.java }}'
+                cache: 'gradle'
+          - name: Java Tests
+            id: tests
+            run: set -o pipefail && SPRING_PROFILES_INCLUDE=postgres ./gradlew --console=plain test jacocoTestReport -x webapp jacocoTestCoverageVerification | tee tests.log
+          - name: Print failed tests
+            if: failure()
+            run: cat tests.log | grep "Test >.* FAILED" || [[ $? == 1 ]]
+          - name: Count failed tests
+            id: failedTestCounter
+            if: failure()
+            run: echo "FAILED_TESTS_COUNT=$(cat tests.log | grep "Test >.* FAILED" | wc -l)" >> $GITHUB_OUTPUT
+          - name: Report action failure
+            if: failure()
+            uses: Sibz/github-status-action@v1
+            with:
+                authToken: ${{secrets.GITHUB_TOKEN}}
+                context: 'Test Run - PostgreSQL'
+                description: '❌ ${{ steps.failedTestCounter.outputs.FAILED_TESTS_COUNT }} failed test(s)'
+                state: 'failure'
+                sha: ${{github.event.pull_request.head.sha || github.sha}}
+          - name: Report action success
+            if: success()
+            uses: Sibz/github-status-action@v1
+            with:
+                authToken: ${{secrets.GITHUB_TOKEN}}
+                context: 'Test Run - PostgreSQL'
+                description: '✅ Test succeeded'
+                state: 'success'
+                sha: ${{github.event.pull_request.head.sha || github.sha}}
+          - name: Test Report
+            uses: dorny/test-reporter@v1
+            if: success() || failure()    # run this step even if previous step failed
+            with:
+                name: PostgreSQL Tests
+                path: build/test-results/test/*.xml
+                reporter: java-junit
+          - name: Number of Server Starts
+            if: success() || failure()
+            run: bash supporting_scripts/extract_number_of_server_starts.sh
 
   server-style:
     runs-on: ubuntu-latest
