try to improve performance

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -105,11 +105,11 @@ jobs:
             run: set -o pipefail && SPRING_PROFILES_INCLUDE=mysql ./gradlew --console=plain test jacocoTestReport -x webapp jacocoTestCoverageVerification | tee tests.log
           - name: Print failed tests
             if: failure()
-            run: cat tests.log | grep "Test >.* FAILED" || [[ $? == 1 ]]
+            run: grep "Test >.* FAILED" tests.log || echo "No failed tests."
           - name: Count failed tests
             id: failedTestCounter
             if: failure()
-            run: echo "FAILED_TESTS_COUNT=$(cat tests.log | grep "Test >.* FAILED" | wc -l)" >> $GITHUB_OUTPUT
+            run: echo "FAILED_TESTS_COUNT=$(grep "Test >.* FAILED" tests.log | wc -l)" >> $GITHUB_OUTPUT
           - name: Report action failure
             if: failure()
             uses: Sibz/github-status-action@v1
@@ -159,11 +159,11 @@ jobs:
             run: set -o pipefail && SPRING_PROFILES_INCLUDE=postgres ./gradlew --console=plain test jacocoTestReport -x webapp jacocoTestCoverageVerification | tee tests.log
           - name: Print failed tests
             if: failure()
-            run: cat tests.log | grep "Test >.* FAILED" || [[ $? == 1 ]]
+            run: grep "Test >.* FAILED" tests.log || echo "No failed tests."
           - name: Count failed tests
             id: failedTestCounter
             if: failure()
-            run: echo "FAILED_TESTS_COUNT=$(cat tests.log | grep "Test >.* FAILED" | wc -l)" >> $GITHUB_OUTPUT
+            run: echo "FAILED_TESTS_COUNT=$(grep "Test >.* FAILED" tests.log | wc -l)" >> $GITHUB_OUTPUT
           - name: Report action failure
             if: failure()
             uses: Sibz/github-status-action@v1
