minor improvements

diff --git a/.github/workflows/testserver-deployment.yml b/.github/workflows/testserver-deployment.yml
--- a/.github/workflows/testserver-deployment.yml
+++ b/.github/workflows/testserver-deployment.yml
@@ -12,6 +12,9 @@ on:
       environment_name:
         description: 'Environment to deploy to'
         required: true
+        type: choice
+        options: 
+          - artemis-staging-localci.artemis.cit.tum.de
 
 concurrency: ${{ github.event.inputs.environment_name }}
 
@@ -167,7 +170,12 @@ jobs:
           
           # Verify the file was copied successfully
           echo "[INFO] Verify new WAR file..."
-          $SSH "if [ ! -f /opt/artemis/artemis.war.new ]; then echo 'Error: WAR file not found after copy'; exit 1; fi"
+          $SSH '
+            if [ ! -f /opt/artemis/artemis.war.new ]; then
+              echo "Error: No WAR file found at /opt/artemis/artemis.war.new"
+              exit 1
+            fi
+          '
           
           # Stop Artemis-Service on node
           echo "[INFO] Stop artemis.service ..."
