Print failed tests for h2 + added failing test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -58,6 +58,9 @@ jobs:
         cache: 'gradle'
     - name: Java Tests
       run: ./gradlew --console=plain test jacocoTestReport -x webapp jacocoTestCoverageVerification | tee tests.log
+    - name: Print failed tests
+      if: failure()
+      run: cat tests.log | grep "Test >.* FAILED" || [[ $? == 1 ]]
     - name: "Codacy: Report coverage"
       uses: codacy/codacy-coverage-reporter-action@master
       with:
