further cleanup test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -60,7 +60,7 @@ jobs:
       run: set -o pipefail && ./gradlew --console=plain test jacocoTestReport -x webapp jacocoTestCoverageVerification | tee tests.log
     - name: Print failed tests
       if: failure()
-      run: cat tests.log | grep "Test >.* FAILED" || [[ $? == 1 ]]
+      run: grep "Test >.* FAILED" tests.log || echo "No failed tests."
     - name: "Codacy: Report coverage"
       uses: codacy/codacy-coverage-reporter-action@master
       with:
@@ -109,7 +109,7 @@ jobs:
           - name: Count failed tests
             id: failedTestCounter
             if: failure()
-            run: echo "FAILED_TESTS_COUNT=$(grep "Test >.* FAILED" tests.log | wc -l)" >> $GITHUB_OUTPUT
+            run: echo "FAILED_TESTS_COUNT=$(grep -c "Test >.* FAILED" tests.log)" >> $GITHUB_OUTPUT
           - name: Report action failure
             if: failure()
             uses: Sibz/github-status-action@v1
@@ -163,7 +163,7 @@ jobs:
           - name: Count failed tests
             id: failedTestCounter
             if: failure()
-            run: echo "FAILED_TESTS_COUNT=$(grep "Test >.* FAILED" tests.log | wc -l)" >> $GITHUB_OUTPUT
+            run: echo "FAILED_TESTS_COUNT=$(grep -c "Test >.* FAILED" tests.log)" >> $GITHUB_OUTPUT
           - name: Report action failure
             if: failure()
             uses: Sibz/github-status-action@v1
